name: Format and Build Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Replace with your Node.js version
          cache: 'pnpm'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run format check
      - name: Format check
        run: pnpm run format:check

      # Step 6: Run build check
      - name: Build check
        run: pnpm run build
